### ISSUE TITLE
Migration and breaking changes mitigations

### ISSUE THREAD

**Issue by wiwei** [microsoft/MixedRealityToolkit-Unity#5772]
Filing an issue to that we need to have a proposal written for how we're going to manage breaking changes and other migitations that we need to provide to customers as they upgrade from build to build.

The nature of the MRTK is one where MUCH of the code is public API surface, so by definition many things are potentially breaking. Some changes are tougher to stomach than others, but now that we have a definition for what breaking changes are:

https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/BreakingChanges.html

We need to have some proposal and thoughts for how we can lessen the impact of those sorts of changes on consumers.

**Comment by MenelvagorMilsom** [comment]
So I began trying this in Python (PyYAML) yesterday evening and this morning. Here are some notes so far:
- Reading Unity's YAML files is a little more awkward than expected.
  - From what I can see `%TAG` shorthands in YAML are valid per `---` document and not per file, but Unity files have only one `%TAG` at the top of the file. This causes errors with PyYAML. This should be ok however, we don't need any information from the tags so this line and all !u![0-9]* strings from the start of `---` documents.
  - PyYAML wasn't capturing the `fileID` specified at the beginning of every `---` document. This is needed in order to reference existing objects and fields. This can be amended by converting each `---` document in the file into a YAML object where the name is `_<fileID>`. This way, we only have one document in the YAML string. At the moment I've stripped away some information that I'll need in order to reconstruct the file, but it should be simple to add it in a way that doesn't interfere.
  - Both of these fixes can be done in a single pass over the document. Once these changes have been made to the YAML string, we should be in a position to make the changes we need.
<table>
  <tr>
    <th>Before</th>
    <th>After</th>
  </tr>
  <tr>
    <td nowrap>
      <pre><code>%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!29 &1
OcclusionCullingSettings:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_OcclusionBakeSettings:
    smallestOccluder: 5
    smallestHole: 0.25
    backfaceThreshold: 100
  m_SceneGUID: 00000000000000000000000000000000
  m_OcclusionCullingData: {fileID: 0}</code></pre>
    </td>
    <td nowrap>
      <pre><code>%YAML 1.1
---
_1:
  OcclusionCullingSettings:
    m_ObjectHideFlags: 0
    serializedVersion: 2
    m_OcclusionBakeSettings:
      smallestOccluder: 5
      smallestHole: 0.25
      backfaceThreshold: 100
    m_SceneGUID: 00000000000000000000000000000000
    m_OcclusionCullingData: {fileID: 0}</code></pre>
    </td>
  </tr>
</table>

- I also investigated [unityparser](https://pypi.org/project/unityparser/), it looked promising, but doesn't work for scenes.
- I was thinking we could define our patches in YAML files too. As I see it, there are only six possible changes to Unity YAML files that we'll need to make. Here's an example of a patch for a BoundingBox change I've made:
```yaml
--- # Patch for moving min/max scaling from BoundingBox to TransformScaleHandler
versions:
  from: 2.0.0
  to: 2.1.0
components:
  - name: BoundingBox
    id: 23f9be7a3cb53794ead8b55e784b65aa
  - name: TransformScaleHandler
    id: 820f94d57893bf843a0cd6d93313fe6d
actions:
  addField: []
  deleteField: 
    - component: BoundingBox
      name: scaleMinimum
    - component: BoundingBox    
      name: scaleMaximum
  renameField: []
  modifyField: []
  addComponent: 
    - conditions:
        has: [BoundingBox]
        doesNotHave: [TransformScaleHandler]
      component:
        unityFields: {}
        componentFields:
          targetTransform: '{{{ MonoBehaviour<BoundingBox>::targetObject::Transform }}}'
          scaleMinimum: '{{{ MonoBehaviour<BoundingBox>::scaleMinimum }}}'
          scaleMaximum: '{{{ MonoBehaviour<BoundingBox>::scaleMaximum }}}'
          relativeToInitialState: 1
  deleteComponent: []
```

- As you can see, we need some method of referencing existing fields. That's what I'm going to attempt today.

**Comment by MenelvagorMilsom** [comment]
An update:
### Referencing Existing Values
For my test script, I have defined a simple syntax for referencing existing values in the scene. Here's an example:
``` yaml
addField:
    - component: BoundingBox
      name: test
      value: '{{{ MonoBehaviour<BoundingBox>::targetObject::Transform::m_LocalScale::x }}}'
  ```
This is an action (see patch syntax in previous comment). The value can be a raw value, or one of these reference strings, marked by triple curly braces. are specified

**Comment by MenelvagorMilsom** [comment]
@wiwei an update:
### Referencing existing values
For my test script, I have defined a simple syntax for referencing existing values in the scene. Here's an example:
``` yaml
addField:
    - component: BoundingBox
      name: test
      value: '{{{ MonoBehaviour<BoundingBox>::targetObject::Transform::m_LocalScale::x }}}'
  ```
This is an action (see patch syntax in previous comment). The value can be a raw value, or one of these reference strings, marked by triple curly braces. This is the current working syntax:
- The links in the search are read left to right and are delimited by double colon `::`.
- The search will attempt to find the _current link_ in the _current object_: 
  - If _current object_ is a fileID, _current object_ will be set to the object for that fileID before we do the following steps. 
  - If _current link_ is found in _current object_ it will set _current object_ to be the object under _current link_. 
  - If not found and _current object_ is a GameObject, search the _current objects_ components for a object that contains _current link_.
- The initial _current object_ is always the GameObject of the component being modified.
- MonoBehaviours require additional information to be found. The script type of the MonoBehaviour should be provided in angle brackets (e.g. MonoBehaviour\<BoundingBox\>).
- If the final link ends on a GameObject or Component, set _current object_ to be it's fileID.

So if we look at the sample string above:
- **MonoBehaviour\<BoundingBox\>**: Not found in the initial GameObject, but it is found in the objects components, _current object_ set to this MonoBehaviour object.
- **targetObject**: Found in _current object_. Set _current object_ to value at targetObject.
- **Transform**: _Current object_ is a fileID, so we reset _current object_ to be the object at this fileID (in this case, it happens to be a GameObject). We then try to find Transform and can't, but we do find it in the GameObjects components. Set _current object_ to be this Transform component.
- **m_LocalScale**: Found in _current object_. Set _current object_ to value at m_LocalScale.
- **x**: Found in _current object_. Set _current object_ to value at x.

So I think I have most of this working; I have yet to implement a few things. There currently no way to find a value in an array. Also, if objects in this chain are part of a prefab, things start falling apart. I can look into these things soon, but just wanted some feedback on this approach.

If we're able to reference existing values in the UnityAsset will the 6 actions I gave in my comment yesterday be enough to specify a patch?

### Is Python the right choice?
So Python has been great for prototyping this, but is it desirable to add a Python dependency for migration? Is it alright to expect users to install Python just to upgrade their projects?

Also, are these migration tools something that we want to add testing for? If so that adds a dependency on Python for our build agents.

I don't necessarily think these are issues, but I thought it was worth chatting with you about it before committing too much to Python.
